### ISSUE TITLE
Expression transfer

### ISSUE THREAD

**Issue by heiha324** [Zielon/INSTA#37]
Do you know how to use one person's facial expressions to drive another person's model?

**Comment by Zielon** [comment]
Yes, you need to use relative expressions. In the other case the radiance field will contain a lot of artifacts since absolute expression transfer will change the face shape as well. 

Steps:
1) Select a neutral face from the source and target. (the expressions and shape are not disentangled)
2) Calculate delta expression (selected neutral expression - expressions).
3) Transfer deltas to the neutral face in the target

You can take a look here [NeRFace](https://github.com/gafniguy/4D-Facial-Avatars/blob/f687d3be0b15dc7bdcae0a31cf8935987af6863e/nerface_code/nerf-pytorch/real_to_nerf.py#L592) to see how it is done.
